### ISSUE TITLE
Anki 2.1

### ISSUE THREAD

**Issue by RisingOrange** [Wandaymo/anki-uppercase-lowercase#1]
Hello, me and other people would like to use your add-on. Could you make it compatible with the current version of Anki 2.1? If you are not interested in doing it are you okay with me forking, updating it and uploading to ankiweb? Or should I make a pull request?

**Comment by Artset08** [comment]
Is it possible to open the subject again ? 
I'm really interested by this addon which could be really helpful. I have the 2.1.26 version of Anki.
